/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useBox } from '@react-three/cannon'
import { useGLTF } from '@react-three/drei'

export default function TrafficCone({ args = [0.3, 0.8, 0.3], ...props }) {
  const { nodes, materials } = useGLTF('/traffic-cone.gltf')

  const [ref] = useBox(() => ({ args, mass: 3, ...props }))

  return (
    <group ref={ref} dispose={null}>
      <group position={[0, -0.38, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={nodes.Cylinder_2.material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/traffic-cone.gltf')
